INSERT INTO fortune (id, text) VALUES (0, 'A beautiful, smart, and loving person will be coming into your life.');
INSERT INTO fortune (id, text) VALUES (1, 'A dubious friend may be an enemy in camouflage.');
INSERT INTO fortune (id, text) VALUES (2, 'A faithful friend is a strong defense.');
INSERT INTO fortune (id, text) VALUES (3, 'A feather in the hand is better than a bird in the air.');
INSERT INTO fortune (id, text) VALUES (4, 'A fresh start will put you on your way.');
INSERT INTO fortune (id, text) VALUES (5, 'A friend asks only for your time not your money.');
INSERT INTO fortune (id, text) VALUES (6, 'A friend is a present you give yourself.');
INSERT INTO fortune (id, text) VALUES (7, 'A gambler not only will lose what he has, but also will lose what he doesn’t have.');
INSERT INTO fortune (id, text) VALUES (8, 'A golden egg of opportunity falls into your lap this month.');
INSERT INTO fortune (id, text) VALUES (9, 'A good friendship is often more important than a passionate romance.');
INSERT INTO fortune (id, text) VALUES (10, 'A good time to finish up old tasks.');
INSERT INTO fortune (id, text) VALUES (11, 'A hunch is creativity trying to tell you something.');
INSERT INTO fortune (id, text) VALUES (12, 'A lifetime friend shall soon be made.');
INSERT INTO fortune (id, text) VALUES (13, 'A lifetime of happiness lies ahead of you.');
INSERT INTO fortune (id, text) VALUES (14, 'A light heart carries you through all the hard times.');
INSERT INTO fortune (id, text) VALUES (15, 'A new perspective will come with the new year.');
INSERT INTO fortune (id, text) VALUES (16, 'A person is never to (sic) old to learn.');
INSERT INTO fortune (id, text) VALUES (17, 'A person of words and not deeds is like a garden full of weeds.');
INSERT INTO fortune (id, text) VALUES (18, 'A pleasant surprise is waiting for you.');
INSERT INTO fortune (id, text) VALUES (19, 'A short pencil is usually better than a long memory any day.');
INSERT INTO fortune (id, text) VALUES (20, 'A small donation is call for. It’s the right thing to do.');
INSERT INTO fortune (id, text) VALUES (21, 'A smile is your personal welcome mat.');
INSERT INTO fortune (id, text) VALUES (22, 'A smooth long journey! Great expectations.');
INSERT INTO fortune (id, text) VALUES (23, 'A soft voice may be awfully persuasive.');
INSERT INTO fortune (id, text) VALUES (24, 'A truly rich life contains love and art in abundance.');
INSERT INTO fortune (id, text) VALUES (25, 'Accept something that you cannot change, and you will feel better.');